PUT http://localhost:3001/api/readinglists/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kYXczQG1haWwubmV0IiwiaWQiOjEsImlhdCI6MTcxODEwNDA2OSwiZXhwIjoxNzE4MTA3NjY5fQ.bd1vxFnDbQr8_ylToZ_lzh_4FFmr35ViDjzf7VrS6ZA

{
  "read": true
}