POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1MGE5ZGI1ZWI4NDIyMTM1NjEyYTc3NiIsImlhdCI6MTY5NTM2ODQxOCwiZXhwIjoxNjk1MzcyMDE4fQ.uIjP7ottcQtkussRoe0N-GpPMYLS_LnD9qeq4Y9-j1A

{
    "title":"rest t10",
    "author":"rest a10",
    "url":"rest u10",
    "likes":10
}

