PUT http://localhost:3003/api/blogs/6511b338a3b36c56326a2f73
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjY1MmVjOGZjNTM4ZWE4MmY2MDdkNjgyMSIsImlhdCI6MTY5NzY0OTU4MCwiZXhwIjoxNjk3NjUzMTgwfQ.mvT2nU5NQRjpzHORCuAFdiG9oqMgV1NeK0pljP_B8sI

{
    "title":"rest t33 upd2",
    "author":"rest a33",
    "url":"rest u33",
    "likes": 33
}

