POST http://localhost:3003/api/blogs
Content-Type: application/json
# to comment in VSCode on mac use shift+cmd+7
# 
# token expired / jwt expired
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjY1MGRlMTY4MDYyMTRjYzQ1NjgzODEyNyIsImlhdCI6MTY5NjA5MDcyNCwiZXhwIjoxNjk2MDk0MzI0fQ.SVK1SUg-qQRhONExNvJkPG43C2etVcgY3TR6GcU9nRY
# 
# invalid token
# Authorization: Bearer byJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjY1MGRlMTY4MDYyMTRjYzQ1NjgzODEyNyIsImlhdCI6MTY5NjA5MDcyNCwiZXhwIjoxNjk2MDk0MzI0fQ.SVK1SUg-qQRhONExNvJkPG43C2etVcgY3TR6GcU9nRY
#                       e
# 
# unknown / "error": {}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI4InVzZXIiLCJpZCI6IjY1MGRlMTY4MDYyMTRjYzQ1NjgzODEyNyIsImlhdCI6MTY5NjA5MDcyNCwiZXhwIjoxNjk2MDk0MzI0fQ.SVK1SUg-qQRhONExNvJkPG43C2etVcgY3TR6GcU9nRY
#                                                                           6
# invalid algorithm
# Authorization: Bearer eyJhbzciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjY1MGRlMTY4MDYyMTRjYzQ1NjgzODEyNyIsImlhdCI6MTY5NjA5MDcyNCwiZXhwIjoxNjk2MDk0MzI0fQ.SVK1SUg-qQRhONExNvJkPG43C2etVcgY3TR6GcU9nRY
#                            G
# 
# invalid signature
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZcIiLCJpZCI6IjY1MGRlMTY4MDYyMTRjYzQ1NjgzODEyNyIsImlhdCI6MTY5NjA5MDcyNCwiZXhwIjoxNjk2MDk0MzI0fQ.SVK1SUg-qQRhONExNvJkPG43C2etVcgY3TR6GcU9nRY
#                                                                                 X
# 
# jwt malformed
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6MTY5NjA5hONExNvJkPG43C2etVcgY3TR6GcU9nRY

{
    "title":"rest t25",
    "author":"rest a25",
    "url":"rest u25",
    "likes":25
}

