POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMiIsImlkIjoyLCJpYXQiOjE3MTc4NTQ1MTd9.hYt3sldeZnzmLR0THtE5hbJLlg8h-nVPwIwUC6QCBkE

{
  "content":"note 6",
  "important":false
}
